---
- job:
    name: rdopkg-base
    pre-run: playbooks/base.yaml
    parent: tox
    abstract: true
    required-projects:
      - distroinfo

- job:
    name: rdopkg-base-py39
    parent: rdopkg-base
    abstract: true
    nodeset:
      nodes:
        - name: cloud-centos-9-stream
          label: cloud-centos-9-stream

- job:
    name: rdopkg-base-py312
    parent: rdopkg-base
    abstract: true
    nodeset:
      nodes:
        - name: cloud-fedora-39
          label: cloud-fedora-39

- job:
    name: rdopkg-base-coverage-py39
    parent: rdopkg-base-py39
    post-run: playbooks/fetch-coverage.yaml
    success-url: coverage/index.html

- job:
    name: rdopkg-base-coverage-py312
    parent: rdopkg-base-py312
    post-run: playbooks/fetch-coverage.yaml
    success-url: coverage/index.html

- job:
    name: rdopkg-py39-tests
    parent: rdopkg-base-coverage-py39
    description: rdopkg unit and feature tests on python3.9
    vars:
      tox_envlist: py39-unit,py39-feature,py39-cover

- job:
    name: rdopkg-py312-tests
    parent: rdopkg-base-coverage-py312
    description: rdopkg unit and feature tests on python3.12
    vars:
      tox_envlist: py312-unit,py312-feature,py312-cover

- job:
    name: rdopkg-py39-integration
    parent: rdopkg-base-py39
    description: rdopkg unit and feature tests on python3.9
    vars:
      tox_envlist: py39-integration

- job:
    name: rdopkg-py312-integration
    parent: rdopkg-base-py312
    description: rdopkg unit and feature tests on python3.12
    vars:
      tox_envlist: py312-integration

- job:
    name: rdopkg-lint
    parent: rdopkg-base-py312
    description: rdopkg linting
    vars:
      tox_envlist: lint

- job:
    name: rdopkg-install-epel-9
    description: install rdopkg with epel
    run: playbooks/install-test-epel-9.yaml
    nodeset:
      nodes:
        - name: cloud-centos-9-stream
          label: cloud-centos-9-stream

- job:
    name: rdopkg-dlrn-master
    parent: dlrn-base
    timeout: 3600
    description: rdopkg integration tests with DLRN master
    run: playbooks/dlrn-master.yaml
    nodeset:
      nodes:
        - name: cloud-centos-9-stream
          label: cloud-centos-9-stream
    required-projects:
      - DLRN

- project:
    name: rdopkg
    check:
      jobs:
        - rdopkg-py39-tests:
            voting: false
        - rdopkg-py39-integration
        - rdopkg-py312-tests:
            voting: false
        - rdopkg-py312-integration
        - rdopkg-lint
        - rdopkg-dlrn-master
    gate:
      jobs:
        - rdopkg-py39-tests:
            voting: false
        - rdopkg-py39-integration
        - rdopkg-py312-tests:
            voting: false
        - rdopkg-py312-integration
        - rdopkg-lint
        - rdopkg-dlrn-master
    periodic:
      jobs:
        - rdopkg-install-epel-9
    release:
      jobs:
        - upload-pypi
