---
- job:
    name: rdopkg-base
    pre-run: playbooks/base.yaml
    parent: tox
    abstract: true

- job:
    name: rdopkg-base-py2
    parent: rdopkg-base
    abstract: true
    nodeset:
      nodes:
        - name: test-node
          label: centos-oci

- job:
    name: rdopkg-base-py3
    parent: rdopkg-base
    abstract: true
    nodeset:
      nodes:
        - name: test-node
          label: f27-oci

- job:
    name: rdopkg-py2-centos-7
    parent: rdopkg-base-py2
    description: rdopkg unit and feature tests on python2
    vars:
      tox_envlist: py2-unit,py2-feature

- job:
    name: rdopkg-py3-fedora-27
    parent: rdopkg-base-py3
    description: rdopkg unit and feature tests on python3
    vars:
      tox_envlist: py3-unit,py3-feature

- job:
    name: rdopkg-py2-integration
    parent: rdopkg-base-py2
    description: rdopkg integration tests on python2
    vars:
      tox_envlist: py2-integration

- job:
    name: rdopkg-py3-integration
    parent: rdopkg-base-py3
    description: rdopkg integration tests on python3
    vars:
      tox_envlist: py3-integration

- job:
    name: rdopkg-codestyle
    parent: rdopkg-base-py2
    description: rdopkg code style checks
    vars:
      tox_envlist: pycodestyle

- job:
    name: rdopkg-install-epel-7
    description: install rdopkg with epel-7
    run: playbooks/install-test-epel-7.yaml
    nodeset:
      nodes:
        - name: test-node
          label: dib-centos-7

- job:
    name: rdopkg-dlrn-master
    parent: dlrn-base
    description: rdopkg integration tests with DLRN master
    run: playbooks/dlrn-master.yaml
    required-projects:
      - DLRN

- project:
    name: rdopkg
    check:
      jobs:
        - rdopkg-py2-centos-7
        - rdopkg-py3-fedora-27
        - rdopkg-py2-integration
        - rdopkg-py3-integration
        - rdopkg-codestyle
        - rdopkg-dlrn-master
    gate:
      jobs:
        - rdopkg-py2-centos-7
        - rdopkg-py3-fedora-27
        - rdopkg-py2-integration
        - rdopkg-py3-integration
        - rdopkg-codestyle
        - rdopkg-dlrn-master
    periodic:
      jobs:
        - rdopkg-install-epel-7
    release:
      jobs:
        - upload-pypi
