---
- hosts: all
  tasks:
    - name: Configure git user for testing
      command: "{{ item }}"
      with_items:
        - git config --global user.email zuul@softwarefactory-project.io
        - git config --global user.name 'CI Test Bot'

    - name: Ensure virtualenv < 20 is installed for CentOS 7
      shell: |
        pip uninstall -y virtualenv 
        pip install 'virtualenv<20'
      become: true
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version | int == 7        
