---
- hosts: all
  tasks:
    - name: Fetch coverage report if any
      synchronize:
        src: "{{ zuul.project.src_dir }}/htmlcov/"
        mode: pull
        dest: "{{ zuul.executor.log_root }}/coverage/"
