---
- hosts: all
  tasks:
    - name: Ensure zuul-output coverage dir
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/coverage/"
        state: directory

    - name: Fetch coverage report if any
      copy:
        src: "{{ zuul.project.src_dir }}/htmlcov/"
        dest: "{{ ansible_user_dir }}/zuul-output/logs/coverage/"
        remote_src: true

    - name: Fetch coverage report if any
      synchronize:
        mode: pull
        src: "{{ zuul.project.src_dir }}/htmlcov/"
        dest: "{{ zuul.executor.log_root }}/coverage/"
